2 Parcia Integracion/Controllers/ActivosFijosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _2_Parcia_Integracion.Data;
using _2_Parcia_Integracion.Models;
using Microsoft.AspNetCore.Authorization;

namespace _2_Parcia_Integracion.Controllers
{
    [Authorize]
    public class ActivosFijosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ActivosFijosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ActivosFijos
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ActivosFijos.Include(a => a.Departamento).Include(a => a.Tipo_Activo);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ActivosFijos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activosFijos = await _context.ActivosFijos
                .Include(a => a.Departamento)
                .Include(a => a.Tipo_Activo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (activosFijos == null)
            {
                return NotFound();
            }

            return View(activosFijos);
        }

        // GET: ActivosFijos/Create
        public IActionResult Create()
        {
            ViewData["DepartamentoID"] = new SelectList(_context.Set<Departamento>(), "Id", "Descripcion");
            ViewData["Tipo_ActivoID"] = new SelectList(_context.Set<TipoDeActivo>(), "Id", "Descripcion");
            return View();
        }

        // POST: ActivosFijos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descripcion,DepartamentoID,Tipo_ActivoID,Fecha_Registro,Valor_Compra,Depreciacion_Acumulada")] ActivosFijos activosFijos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(activosFijos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartamentoID"] = new SelectList(_context.Set<Departamento>(), "Id", "Descripcion", activosFijos.DepartamentoID);
            ViewData["Tipo_ActivoID"] = new SelectList(_context.Set<TipoDeActivo>(), "Id", "Descripcion", activosFijos.Tipo_ActivoID);
            return View(activosFijos);
        }

        // GET: ActivosFijos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activosFijos = await _context.ActivosFijos.FindAsync(id);
            if (activosFijos == null)
            {
                return NotFound();
            }
            ViewData["DepartamentoID"] = new SelectList(_context.Set<Departamento>(), "Id", "Descripcion", activosFijos.DepartamentoID);
            ViewData["Tipo_ActivoID"] = new SelectList(_context.Set<TipoDeActivo>(), "Id", "Descripcion", activosFijos.Tipo_ActivoID);
            return View(activosFijos);
        }

        // POST: ActivosFijos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Descripcion,DepartamentoID,Tipo_ActivoID,Fecha_Registro,Valor_Compra,Depreciacion_Acumulada")] ActivosFijos activosFijos)
        {
            if (id != activosFijos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(activosFijos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActivosFijosExists(activosFijos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartamentoID"] = new SelectList(_context.Set<Departamento>(), "Id", "Descripcion", activosFijos.DepartamentoID);
            ViewData["Tipo_ActivoID"] = new SelectList(_context.Set<TipoDeActivo>(), "Id", "Descripcion", activosFijos.Tipo_ActivoID);
            return View(activosFijos);
        }

        // GET: ActivosFijos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activosFijos = await _context.ActivosFijos
                .Include(a => a.Departamento)
                .Include(a => a.Tipo_Activo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (activosFijos == null)
            {
                return NotFound();
            }

            return View(activosFijos);
        }

        // POST: ActivosFijos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var activosFijos = await _context.ActivosFijos.FindAsync(id);
            _context.ActivosFijos.Remove(activosFijos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActivosFijosExists(int id)
        {
            return _context.ActivosFijos.Any(e => e.Id == id);
        }
    }
}

2 Parcia Integracion/Controllers/DepreciacionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _2_Parcia_Integracion.Data;
using _2_Parcia_Integracion.Models;
using Microsoft.AspNetCore.Authorization;

namespace _2_Parcia_Integracion.Controllers
{
    [Authorize]
    public class DepreciacionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DepreciacionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Depreciacions
        public async Task<IActionResult> Index()
        {
            return View(await _context.Depreciacion.ToListAsync());
        }

        // GET: Depreciacions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var depreciacion = await _context.Depreciacion
                .FirstOrDefaultAsync(m => m.Id == id);
            if (depreciacion == null)
            {
                return NotFound();
            }

            return View(depreciacion);
        }

        // GET: Depreciacions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Depreciacions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Anio_Proceso,Mes_Proceso,Activo_FijoID,Fecha_Proceso,Moto_Depreciado,Deprecion_Acumulada,Cuenta_Compra,Cuenta_Depreciacion")] Depreciacion depreciacion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(depreciacion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(depreciacion);
        }

        // GET: Depreciacions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var depreciacion = await _context.Depreciacion.FindAsync(id);
            if (depreciacion == null)
            {
                return NotFound();
            }
            return View(depreciacion);
        }

        // POST: Depreciacions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Anio_Proceso,Mes_Proceso,Activo_FijoID,Fecha_Proceso,Moto_Depreciado,Deprecion_Acumulada,Cuenta_Compra,Cuenta_Depreciacion")] Depreciacion depreciacion)
        {
            if (id != depreciacion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(depreciacion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepreciacionExists(depreciacion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(depreciacion);
        }

        // GET: Depreciacions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var depreciacion = await _context.Depreciacion
                .FirstOrDefaultAsync(m => m.Id == id);
            if (depreciacion == null)
            {
                return NotFound();
            }

            return View(depreciacion);
        }

        // POST: Depreciacions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var depreciacion = await _context.Depreciacion.FindAsync(id);
            _context.Depreciacion.Remove(depreciacion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepreciacionExists(int id)
        {
            return _context.Depreciacion.Any(e => e.Id == id);
        }
    }
}

2 Parcia Integracion/Controllers/EmpleadoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _2_Parcia_Integracion.Data;
using _2_Parcia_Integracion.Models;
using Microsoft.AspNetCore.Authorization;

namespace _2_Parcia_Integracion.Controllers
{
    [Authorize]
    public class EmpleadoesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmpleadoesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Empleadoes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Empleado.Include(e => e.Departamento);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Empleadoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleado
                .Include(e => e.Departamento)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // GET: Empleadoes/Create
        public IActionResult Create()
        {
            ViewData["DepartamentoID"] = new SelectList(_context.Departamento, "Id", "Descripcion");
            return View();
        }

        // POST: Empleadoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Cedula,DepartamentoID,Tipo_Persona,Fecha_Ingreso,Estado")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                _context.Add(empleado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartamentoID"] = new SelectList(_context.Departamento, "Id", "Descripcion", empleado.DepartamentoID);
            return View(empleado);
        }

        // GET: Empleadoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleado.FindAsync(id);
            if (empleado == null)
            {
                return NotFound();
            }
            ViewData["DepartamentoID"] = new SelectList(_context.Departamento, "Id", "Descripcion", empleado.DepartamentoID);
            return View(empleado);
        }

        // POST: Empleadoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,Cedula,DepartamentoID,Tipo_Persona,Fecha_Ingreso,Estado")] Empleado empleado)
        {
            if (id != empleado.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empleado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpleadoExists(empleado.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartamentoID"] = new SelectList(_context.Departamento, "Id", "Descripcion", empleado.DepartamentoID);
            return View(empleado);
        }

        // GET: Empleadoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleado
                .Include(e => e.Departamento)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // POST: Empleadoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var empleado = await _context.Empleado.FindAsync(id);
            _context.Empleado.Remove(empleado);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpleadoExists(int id)
        {
            return _context.Empleado.Any(e => e.Id == id);
        }
    }
}

2 Parcia Integracion/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using _2_Parcia_Integracion.Models;

namespace _2_Parcia_Integracion.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

2 Parcia Integracion/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenidos</h1>

    <p class="my-5">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Sit amet commodo nulla facilisi nullam vehicula ipsum a arcu. Cum sociis natoque penatibus et magnis dis parturient montes. Consequat semper viverra nam libero justo laoreet. Lacinia quis vel eros donec ac odio tempor orci. Tortor consequat id porta nibh venenatis. Id leo in vitae turpis massa sed elementum. Varius morbi enim nunc faucibus a pellentesque sit amet. Ipsum dolor sit amet consectetur adipiscing elit duis. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Tristique sollicitudin nibh sit amet commodo nulla facilisi. Urna condimentum mattis pellentesque id nibh tortor id. Sed tempus urna et pharetra pharetra. Malesuada proin libero nunc consequat interdum varius sit amet mattis. In mollis nunc sed id semper. Enim lobortis scelerisque fermentum dui. Natoque penatibus et magnis dis parturient montes.
    </p>
</div>

<hr />

<div class="row mt-5">
    <div class="col-4">
        <div class="card bg-light">
            <div class="card-body">
                <img class="float-left card-img-top" src="~/img/enterprise.svg" alt="Employee image cap" style="height:75px;">
                <h5 class="card-title text-center">
                    <a class="text-dark" asp-controller="Departamentoes" asp-action="Index">Departamentos</a>
                </h5>
                <hr />
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card bg-light">
            <div class="card-body">
                <img class="float-left card-img-top" src="~/img/employee.svg" alt="Employee image cap" style="height:75px;">
                <h5 class="card-title text-center">
                    <a class="text-dark" asp-controller="Empleadoes" asp-action="Index">Empleados</a>
                </h5>
                <hr />
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card bg-light">
            <div class="card-body">
                <img class="float-left card-img-top" src="~/img/cargo.svg" alt="Employee image cap" style="height:75px;">
                <h5 class="card-title text-center">
                    <a class="text-dark" asp-controller="TipoDeActivoes" asp-action="Index">Tipos de Activos</a>
                </h5>
                <hr />
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
    </div>
</div>

<div class="row mt-5">
    <div class="col-4">
        <div class="card bg-light">
            <div class="card-body">
                <img class="float-left card-img-top" src="~/img/assets.svg" alt="Employee image cap" style="height:75px;">
                <h5 class="card-title text-center">
                    <a class="text-dark" asp-controller="ActivosFijos" asp-action="Index">Activos Fijos</a>
                </h5>
                <hr />
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card bg-light">
            <div class="card-body">
                <img class="float-left card-img-top" src="~/img/depreciation.svg" alt="Employee image cap" style="height:75px;">
                <h5 class="card-title text-center">
                    <a class="text-dark" asp-controller="Depreciacions" asp-action="Index">Depreciacion</a>
                </h5>
                <hr />
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card bg-light">
            <div class="card-body">
                <img class="float-left card-img-top" src="~/img/cargo.svg" alt="Employee image cap" style="height:75px;">
                <h5 class="card-title text-center">
                    <a class="text-dark" asp-controller="" asp-action="">Asiento Contable</a>
                </h5>
                <hr />
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
    </div>
</div>

<style scoped>
    body {
        background-image: linear-gradient(to bottom, #ffffff 10%, #9EE0FF );
    }
</style>